### ISSUE TITLE
Migration to Python 3

### ISSUE THREAD

**Issue by g-weatherill** [GEMScienceTools/gmpe-smtk#64]
With OQ-Engine dropping support for Python 2.7 (https://github.com/gem/oq-engine/issues/2803), the toolkit needs to be ported to Python 3.5

**Comment by daniviga** [comment]
Please not that `gmpe-smtk` is tested by travis but only the installation is tested (still python2) because no tests are provided.

**Comment by g-weatherill** [comment]
Some tests are being added shortly

**Comment by daniviga** [comment]
Closed via https://github.com/GEMScienceTools/gmpe-smtk/pull/78
