### ISSUE TITLE
Support json as a format for internal db for metadata

### ISSUE THREAD

**Issue by g-weatherill** [GEMScienceTools/gmpe-smtk#79]
At present, the internal data storage for a strong motion database is using a Python pickle file for metadata and a set of hdf5 binaries (one per strong motion observation) for the strong motion data itself. This was designed so that the metadata related objects of the database could be loaded into memory directly and all metadata related functions (e.g. querying, selection, adding new attributes) would be available to the user with the strong motion data only being read at the points it is needed (i.e. no need to load many Gbs of data to memory). The downside of this is that the Pickle files themselves are clearly specific only to the Python language, and so this db format cannot be proposed as a potential "standard" for wider use.

Propose to add support for the metadata to be stored in JSON format.

Pros:
* JSON + hdf5 binaries can be proposed as a potential "standard" for strong motion database usage and is not tied to Python specifically
* Clear, explicit and transferable - opens up possibilities for web interactions with metadata

Cons:
* Would needs to instantiate objects from json at loading
* Potentially slower and more memory intensive - could be partly remedied by use of Json iterparse tool (https://pypi.python.org/pypi/ijson/)
* Metadata file larger (factor of 3 - 4) - not the biggest problem as the size of the metadata file is still small compared to the full set of hdf5 binaries (in most cases)
* Scalability issues (seems OK for 20,000 records [e.g. ESM, NGA West 2], but what about 120,000 [ e.g. KiKNet])?

Prototyping underway and would aim to support either pickle or json. Propose a `load_database` function to simplify the loading of the metadata (not relying on the pickle call as it is at the moment) and make it agnostic to the filetype.

**Comment by mmpagani** [comment]
I support the use of json for storing metadata for data interchange. Actual work in the tool I think should still rely on pickled objects (since reading them is much faster).

**Comment by g-weatherill** [comment]
Yes, I suspect that pickled objects will be faster to read (unless the ijson gives a remarkable speedup) - but I will benchmark both using some mid- to large-scale databases and find out.

**Comment by g-weatherill** [comment]
Now addressed by https://github.com/GEMScienceTools/gmpe-smtk/pull/80 - closing
