### ISSUE TITLE
Fix the SMTK to work with current master

### ISSUE THREAD

**Issue by micheles** [GEMScienceTools/gmpe-smtk#81]
https://github.com/gem/oq-engine/pull/3545 broke the SMTK that is using some private methods of the class JB2009CorrelationModel. This is a not a big issue. That change entered after the creation of the engine-3.0 branch, so the SMTK works with the official release. On Monday I will fix the code for master.
We will also need to set the dependencies properly, i.e. the version of the SMTK must be aligned with the version of the engine.

**Comment by g-weatherill** [comment]
I think this is resolved now by https://github.com/GEMScienceTools/gmpe-smtk/pull/84, so closing
